[package]
    edition = "2024"
    name    = "AdwaiGram"
    version = "0.1.0"

[dependencies]
    relm4       = { version = "0.9.1", features = [ "gnome_47", "libadwaita" ] }
    relm4-icons = "0.9.0"
